### ISSUE TITLE
asgiref install error

### ISSUE THREAD

**Issue by Dinosaur-Ceiling** [GISDev01/security-ssid-abi#40]
Attempted to follow the instructions provided for the install and ran into the following below error. 
 
The user requested asgiref==3.2.7
    django 3.1.13 depends on asgiref<4 and >=3.2.10

I attempted to manually install a version of asgiref within the guidelines above but I still keep getting the same error when running the sudo pip3 install -r requirements.txt. 

Any help is appreciated!

**Comment by GISDev01** [comment]
Sorry, just now seeing this. I will try to do a clean install and update the install steps so that it works. 
What OS are you running this on?
